name: home_renovation_interior_design

dataset:
  dialog_json: data/dialog/Home_Renovation_Interior_Design_Open.json
  image_root: data/image

eval:
  mode: open
  output_json: output/results_home_renovation_interior_design.json
  max_questions: 0
  resume_questions: true
